reviews:
  # Enable high-level summaries and sequence diagrams
  high_level_summary: true
  sequence_diagrams: true
  
  # Path-based instructions for better review quality
  path_instructions:
    - path: "src/**/*.ts"
      instructions: |
        Focus on TypeScript best practices, type safety, and performance optimizations.
        Pay special attention to entropy calculations and worker implementations.
        Review error handling and async patterns.
    
    - path: "src/entropy*.ts"
      instructions: |
        Review information theory implementations, mathematical accuracy,
        and performance optimization techniques. Ensure algorithms are correct
        and efficiently implemented.
    
    - path: "*.config.{ts,js}"
      instructions: |
        Review build configuration for optimization opportunities,
        security considerations, and best practices for modern tooling.
    
    - path: "*.md"
      instructions: |
        Review documentation for clarity, completeness, and accuracy.
        Ensure installation instructions are correct and comprehensive.

  # Enable finishing touches
  finishing_touches:
    enabled: true
    
  # Chat settings for interactive feedback
  chat:
    auto_reply: true
    
  # Tools configuration
  tools:
    # Enable advanced analysis tools
    ast-grep:
      essential_rules: true
    
# Knowledge base settings for better context
knowledge_base:
  # Enable web search for up-to-date information
  web_search: true
  
  # Automatically learn from conversations
  learnings: true
  
  # Scan for coding guidelines
  code_guidelines:
    enabled: true
    patterns:
      - "**/.cursorrules"
      - ".github/copilot-instructions.md"
      - "**/CLAUDE.md"
      - "**/.cursor/rules/*"
      - "**/.windsurfrules"
      - "**/.clinerules/*"
      - "**/.rules/*"